# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'
# Define services
services:
  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: pictures_db
      MYSQL_USER: pictures_u
      MYSQL_PASSWORD: pictures_p
      MYSQL_ROOT_PASSWORD: root0808
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - pictures
# Volumes
volumes:
  db-data:
# Networks to be created to facilitate communication between containers
networks:
  pictures: